# Generated by Django 5.2.17 on 2026-10-06 02:19

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Se imprimirá como parte de la decoración de la fiesta.', null=True, upload_to=accounts.models.ruta_foto_perfil, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), accounts.models.validar_tamano_foto], verbose_name='foto de perfil'),
        ),
    ]
