# Generated by Django 5.2.17 on 2026-10-05 03:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoBoleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('cupo', models.PositiveIntegerField(blank=True, help_text='Vacío = sin límite', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'tipo de boleto',
                'verbose_name_plural': 'tipos de boleto',
                'ordering': ('orden', 'precio'),
            },
        ),
        migrations.CreateModel(
            name='VentaBoleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre del comprador')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, help_text='Si se deja vacío se toma el precio del tipo.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='precio unitario')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('genero', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('O', 'Otro'), ('N', 'Prefiero no decir')], default='N', max_length=1, verbose_name='género')),
                ('canal', models.CharField(choices=[('messenger', 'Messenger'), ('instagram', 'Instagram'), ('taquilla', 'Taquilla')], default='messenger', max_length=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='pagado', max_length=10)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True, verbose_name='fecha de venta')),
                ('notas', models.TextField(blank=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='tickets.tipoboleto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'venta de boleto',
                'verbose_name_plural': 'ventas de boletos',
                'ordering': ('-fecha_venta',),
            },
        ),
    ]
