# Generated by Django 5.2.17 on 2026-10-05 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoboleto',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Mujeres'), ('H', 'Hombres')], help_text='Vacío = para todos', max_length=1, verbose_name='aplica a'),
        ),
        migrations.AddField(
            model_name='tipoboleto',
            name='modalidad',
            field=models.CharField(choices=[('gratis', 'Gratis (con registro)'), ('preventa', 'Preventa (compra por chat)'), ('puerta', 'Pago en puerta')], default='preventa', max_length=10),
        ),
    ]
