# Generated by Django 5.2.17 on 2026-10-05 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_venta_codigo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaboleto',
            name='ingreso',
            field=models.DateTimeField(blank=True, null=True, verbose_name='hora de entrada'),
        ),
        migrations.AddField(
            model_name='ventaboleto',
            name='ingreso_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_registradas', to=settings.AUTH_USER_MODEL, verbose_name='entrada registrada por'),
        ),
    ]
