# Generated by Django 5.2.17 on 2026-10-05 03:44

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('costo', 'Costo'), ('gasto', 'Gasto')], max_length=5)),
                ('naturaleza', models.CharField(choices=[('fijo', 'Fijo'), ('variable', 'Variable')], max_length=8)),
                ('categoria', models.CharField(choices=[('renta', 'Renta del lugar'), ('sonido', 'Sonido / DJ'), ('iluminacion', 'Iluminación'), ('decoracion', 'Decoración'), ('bebidas', 'Bebidas'), ('seguridad', 'Seguridad'), ('publicidad', 'Publicidad'), ('staff', 'Staff'), ('permisos', 'Permisos'), ('otros', 'Otros')], default='otros', max_length=12, verbose_name='categoría')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('proveedor', models.CharField(blank=True, max_length=150)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('notas', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'costo / gasto',
                'verbose_name_plural': 'costos y gastos',
                'ordering': ('-fecha', '-creado'),
            },
        ),
    ]
