# Generated by Django 5.2.17 on 2026-10-08 03:52

import django.core.validators
import finances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientofinanciero',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'webp']), finances.models.validar_tamano]),
        ),
    ]
